export type MachineProduct = {
  id: number;
  name: string;
  category: string;
  image: string;
  description: string;
  features: string[];
  power: string;
  workArea: string;
  automation: string;
  stockLabel: string;
  deliveryLabel: string;
};

export const machineProducts: MachineProduct[] = [
  {
    id: 1,
    name: 'Açık Çift Tablalı Sac Kesim Makinesi',
    category: 'Sac Plaka Kesimi',
    image: '/images/1.jpg',
    description:
      'Kesintisiz üretim için tasarlanmıştır, yüksek verimli çift tablalı sac kesim çözümü. Otomatik tabla değişimiyle verimlilik artar.',
    features: ['Çift tablalı sürekli üretim', 'Yüksek hassasiyet', 'Düşük enerji tüketimi'],
    power: '6-12 kW',
    workArea: '1500x3000',
    automation: 'Otomatik tabla',
    stockLabel: 'Stokta',
    deliveryLabel: '3-5 hafta',
  },
  {
    id: 2,
    name: 'Ağır Tip Boru Kesim Makinesi',
    category: 'Boru Kesimi',
    image: '/images/2.jpg',
    description: 'Ağır sanayi uygulamaları için geliştirilmiş, yüksek dayanımlı boru kesim çözümü.',
    features: ['Ağır hizmet tipi yapı', 'Geniş boru çap aralığı', 'Yüksek hassasiyet'],
    power: '6-15 kW',
    workArea: 'Boru çap 20-220mm',
    automation: 'Otomatik yükleme',
    stockLabel: 'Siparişle',
    deliveryLabel: '5-7 hafta',
  },
  {
    id: 3,
    name: 'Boru ve Sac Ä°kisi Bir Arada Lazer Kesim Makinesi',
    category: 'Sac Plaka Kesimi',
    image: '/images/3.jpg',
    description: 'Hem sac hem de boru kesimi için tek çözüm. Ä°ki işlemi tek makinede birleştirir.',
    features: ['Çift amaçlı kullanım', 'Hızlı işlem değişimi', 'Geniş çalışma alanı'],
    power: '6-12 kW',
    workArea: '1500x3000 + boru',
    automation: 'Hızlı değişim',
    stockLabel: 'Stokta',
    deliveryLabel: '4-6 hafta',
  },
  {
    id: 4,
    name: 'Çift Tabla Sac Kesim Makinesi',
    category: 'Sac Plaka Kesimi',
    image: '/images/4.jpg',
    description: 'Kesintisiz üretim için optimize edilmiş, yüksek kapasiteli lazer kesim sistemi.',
    features: ['Kesintisiz üretim', 'Otomatik tabla değişimi', 'Kolay bakım'],
    power: '6-20 kW',
    workArea: '2000x4000',
    automation: 'Çift tabla',
    stockLabel: 'Siparişle',
    deliveryLabel: '6-8 hafta',
  },
  {
    id: 5,
    name: 'Değiştirilebilir Ayna Boru Kesim Makinesi',
    category: 'Boru Kesimi',
    image: '/images/5.jpg',
    description: 'Farklı boru çapları için hızlı ayna değişimi yapabilen esnek üretim çözümü.',
    features: ['Hızlı ayna değişimi', 'Geniş boru çap aralığı', 'Düşük bakım gereksinimi'],
    power: '6-12 kW',
    workArea: 'Boru çap 20-240mm',
    automation: 'Ayna değişimi',
    stockLabel: 'Stokta',
    deliveryLabel: '4-6 hafta',
  },
  {
    id: 6,
    name: 'Demir Kesim Makinesi',
    category: 'Demir Kesimi',
    image: '/images/6.jpg',
    description: 'Sert metaller ve demir kesimi için tasarlanmış yüksek güçlü lazer çözümü.',
    features: ['Yüksek güçlü lazer kaynağı', 'Sert metallerde etkili kesim', 'Güvenli çalışma'],
    power: '12-30 kW',
    workArea: '1500x3000',
    automation: 'Güvenlik paketi',
    stockLabel: 'Siparişle',
    deliveryLabel: '6-9 hafta',
  },
  {
    id: 7,
    name: 'Geniş Tabla Yüksek KW Sac Kesim Makinesi',
    category: 'Sac Plaka Kesimi',
    image: '/images/7.jpg',
    description: 'Büyük ebatlı saclar için yüksek güçlü, endüstriyel lazer kesim çözümü.',
    features: ['Geniş çalışma alanı', 'Yüksek güçlü lazer kaynağı', 'Yüksek kesim hızı'],
    power: '12-30 kW',
    workArea: '2500x6000',
    automation: 'Otomatik yükleme',
    stockLabel: 'Siparişle',
    deliveryLabel: '6-9 hafta',
  },
  {
    id: 8,
    name: 'Küçük Çaplı Tam Otomatik Yükleyici ve Ä°ndirici Boru Kesim Makinesi',
    category: 'Boru Kesimi',
    image: '/images/8.jpg',
    description: 'Küçük çaplı borular için tam otomatik yükleyici/bosaltıcı sistemli çözüm.',
    features: ['Tam otomatik sistem', 'Yüksek üretim hızı', 'Düşük işçilik maliyeti'],
    power: '3-6 kW',
    workArea: 'Boru çap 10-120mm',
    automation: 'Tam otomatik',
    stockLabel: 'Stokta',
    deliveryLabel: '3-5 hafta',
  },
  {
    id: 9,
    name: 'Raylı Sac Kesim Makinesi',
    category: 'Sac Plaka Kesimi',
    image: '/images/9.jpg',
    description: 'Uzun sac levhalar için raylı sistem tasarımıyla yüksek hassasiyet.',
    features: ['Raylı taşıma sistemi', 'Uzun saclarda yüksek hassasiyet', 'Düşük enerji tüketimi'],
    power: '6-15 kW',
    workArea: '2000x8000',
    automation: 'Raylı sistem',
    stockLabel: 'Siparişle',
    deliveryLabel: '7-9 hafta',
  },
  {
    id: 10,
    name: 'Tek Tabla Sac Kesim Makinesi',
    category: 'Sac Plaka Kesimi',
    image: '/images/10.jpg',
    description: 'Küçük ve orta ölçekli işletmeler için ekonomik, verimli tek tablalı çözüm.',
    features: ['Ekonomik çözüm', 'Kompakt tasarım', 'Kolay kullanım'],
    power: '3-6 kW',
    workArea: '1500x3000',
    automation: 'Manuel tabla',
    stockLabel: 'Stokta',
    deliveryLabel: '3-4 hafta',
  },
  {
    id: 11,
    name: 'Yandan Yüklemeli Yarı Otomatik Boru Kesim Makinesi',
    category: 'Boru Kesimi',
    image: '/images/11.jpg',
    description: 'Yandan yükleme ile kolay kullanım sunan yarı otomatik boru kesim çözümü.',
    features: ['Yandan yükleme kolaylığı', 'Yarı otomatik çalışma', 'Kolay bakım'],
    power: '3-6 kW',
    workArea: 'Boru çap 20-160mm',
    automation: 'Yarı otomatik',
    stockLabel: 'Stokta',
    deliveryLabel: '4-6 hafta',
  },
  {
    id: 12,
    name: 'Yarı Otomatik Yüklemeli Boru Kesim Makinesi',
    category: 'Boru Kesimi',
    image: '/images/12.jpg',
    description: 'Yarı otomatik yükleme sistemi ile pratik ve ekonomik boru kesim çözümü.',
    features: ['Yarı otomatik yükleme', 'Kullanım kolaylığı', 'Düşük işletme maliyeti'],
    power: '3-6 kW',
    workArea: 'Boru çap 20-120mm',
    automation: 'Yarı otomatik',
    stockLabel: 'Siparişle',
    deliveryLabel: '5-7 hafta',
  },
];

export const machineProductNames = machineProducts.map((product) => product.name);

