export type MachineProduct = {
  id: number;
  name: string;
  category: string;
  image: string;
  description: string;
  features: string[];
  power: string;
  workArea: string;
  automation: string;
  stockLabel: string;
  deliveryLabel: string;
};

export const machineProducts: MachineProduct[] = [
  {
    id: 1,
    name: 'Acik Cift Tablali Sac Kesim Makinesi',
    category: 'Sac Kesim',
    image: '/images/1.jpg',
    description:
      'Kesintisiz uretim icin tasarlanmis, yuksek verimli cift tablali sac kesim cozumu. Otomatik tabla degisimiyle verimlilik artar.',
    features: ['Cift tablali surekli uretim', 'Yuksek hassasiyet', 'Dusuk enerji tuketimi'],
    power: '6-12 kW',
    workArea: '1500x3000',
    automation: 'Otomatik tabla',
    stockLabel: 'Stokta',
    deliveryLabel: '3-5 hafta',
  },
  {
    id: 2,
    name: 'Agir Tip Boru Kesim Makinesi',
    category: 'Boru Kesim',
    image: '/images/2.jpg',
    description: 'Agir sanayi uygulamalari icin gelistirilmis, yuksek dayanimli boru kesim cozumu.',
    features: ['Agir hizmet tipi yapi', 'Genis boru cap araligi', 'Yuksek hassasiyet'],
    power: '6-15 kW',
    workArea: 'Boru cap 20-220mm',
    automation: 'Otomatik yukleme',
    stockLabel: 'Siparisle',
    deliveryLabel: '5-7 hafta',
  },
  {
    id: 3,
    name: 'Boru ve Sac Ikisi Bir Arada Lazer Kesim Makinesi',
    category: 'Kombine Kesim',
    image: '/images/3.jpg',
    description: 'Hem sac hem de boru kesimi icin tek cozum. Iki islemi tek makinede birlestirir.',
    features: ['Cift amacli kullanim', 'Hizli islem degisimi', 'Genis calisma alani'],
    power: '6-12 kW',
    workArea: '1500x3000 + boru',
    automation: 'Hizli degisim',
    stockLabel: 'Stokta',
    deliveryLabel: '4-6 hafta',
  },
  {
    id: 4,
    name: 'Cift Tabla Sac Kesim Makinesi',
    category: 'Sac Kesim',
    image: '/images/4.jpg',
    description: 'Kesintisiz uretim icin optimize edilmis, yuksek kapasiteli lazer kesim sistemi.',
    features: ['Kesintisiz uretim', 'Otomatik tabla degisimi', 'Kolay bakim'],
    power: '6-20 kW',
    workArea: '2000x4000',
    automation: 'Cift tabla',
    stockLabel: 'Siparisle',
    deliveryLabel: '6-8 hafta',
  },
  {
    id: 5,
    name: 'Degistirilebilir Ayna Boru Kesim Makinesi',
    category: 'Boru Kesim',
    image: '/images/5.jpg',
    description: 'Farkli boru caplari icin hizli ayna degisimi yapabilen esnek uretim cozumu.',
    features: ['Hizli ayna degisimi', 'Genis boru cap araligi', 'Dusuk bakim gereksinimi'],
    power: '6-12 kW',
    workArea: 'Boru cap 20-240mm',
    automation: 'Ayna degisimi',
    stockLabel: 'Stokta',
    deliveryLabel: '4-6 hafta',
  },
  {
    id: 6,
    name: 'Demir Kesim Makinesi',
    category: 'Ozel Kesim',
    image: '/images/6.jpg',
    description: 'Sert metaller ve demir kesimi icin tasarlanmis yuksek guclu lazer cozumu.',
    features: ['Yuksek guclu lazer kaynagi', 'Sert metalde etkili kesim', 'Guvenli calisma'],
    power: '12-30 kW',
    workArea: '1500x3000',
    automation: 'Guvenlik paketi',
    stockLabel: 'Siparisle',
    deliveryLabel: '6-9 hafta',
  },
  {
    id: 7,
    name: 'Genis Tabla Yuksek KW Sac Kesim Makinesi',
    category: 'Sac Kesim',
    image: '/images/7.jpg',
    description: 'Buyuk ebatli saclar icin yuksek guclu, endustriyel lazer kesim cozumu.',
    features: ['Genis calisma alani', 'Yuksek guclu lazer kaynagi', 'Yuksek kesim hizi'],
    power: '12-30 kW',
    workArea: '2500x6000',
    automation: 'Otomatik yukleme',
    stockLabel: 'Siparisle',
    deliveryLabel: '6-9 hafta',
  },
  {
    id: 8,
    name: 'Kucuk Capli Tam Otomatik Yukleme ve Indirme Boru Kesim Makinesi',
    category: 'Boru Kesim',
    image: '/images/8.jpg',
    description: 'Kucuk capli borular icin tam otomatik yukleme/bosaltma sistemli cozum.',
    features: ['Tam otomatik sistem', 'Yuksek uretim hizi', 'Dusuk iscilik maliyeti'],
    power: '3-6 kW',
    workArea: 'Boru cap 10-120mm',
    automation: 'Tam otomatik',
    stockLabel: 'Stokta',
    deliveryLabel: '3-5 hafta',
  },
  {
    id: 9,
    name: 'Rayli Sac Kesim Makinesi',
    category: 'Sac Kesim',
    image: '/images/9.jpg',
    description: 'Uzun sac levhalar icin rayli sistem tasarimiyla yuksek hassasiyet.',
    features: ['Rayli tasima sistemi', 'Uzun saclarda yuksek hassasiyet', 'Dusuk enerji tuketimi'],
    power: '6-15 kW',
    workArea: '2000x8000',
    automation: 'Rayli sistem',
    stockLabel: 'Siparisle',
    deliveryLabel: '7-9 hafta',
  },
  {
    id: 10,
    name: 'Tek Tabla Sac Kesim Makinesi',
    category: 'Sac Kesim',
    image: '/images/10.jpg',
    description: 'Kucuk ve orta olcekli isletmeler icin ekonomik, verimli tek tablali cozum.',
    features: ['Ekonomik cozum', 'Kompakt tasarim', 'Kolay kullanim'],
    power: '3-6 kW',
    workArea: '1500x3000',
    automation: 'Manuel tabla',
    stockLabel: 'Stokta',
    deliveryLabel: '3-4 hafta',
  },
  {
    id: 11,
    name: 'Yandan Yuklemeli Yari Otomatik Boru Kesim Makinesi',
    category: 'Boru Kesim',
    image: '/images/11.jpg',
    description: 'Yandan yukleme ile kolay kullanim sunan yari otomatik boru kesim cozumu.',
    features: ['Yandan yukleme kolayligi', 'Yari otomatik calisma', 'Kolay bakim'],
    power: '3-6 kW',
    workArea: 'Boru cap 20-160mm',
    automation: 'Yari otomatik',
    stockLabel: 'Stokta',
    deliveryLabel: '4-6 hafta',
  },
  {
    id: 12,
    name: 'Yari Otomatik Yuklemeli Boru Kesim Makinesi',
    category: 'Boru Kesim',
    image: '/images/12.jpg',
    description: 'Yari otomatik yukleme sistemi ile pratik ve ekonomik boru kesim cozumu.',
    features: ['Yari otomatik yukleme', 'Kullanim kolayligi', 'Dusuk isletme maliyeti'],
    power: '3-6 kW',
    workArea: 'Boru cap 20-120mm',
    automation: 'Yari otomatik',
    stockLabel: 'Siparisle',
    deliveryLabel: '5-7 hafta',
  },
];

export const machineProductNames = machineProducts.map((product) => product.name);
