-- Extend OrderStatus enum with shipping flow
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'RECEIVED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'SHIPPED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'IN_TRANSIT';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'DELIVERED';
